### ISSUE TITLE
Punkte-Berechnung von Geocaches

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#10]
Bei einigen Geocaches wurden noch keine Wertungspunkt berechnet.

Siehe: http://sc.verfriemelt.org/index.php/detail/geocacher/6260301

**Comment by rstweb** [comment]
Das ist richtig. Es sind noch nicht alle Logs eingeladen. Es fehlen noch die Logs von rd. 4.200 Caches. Das sollte sich dann in den nächsten 2-3 Tagen erledigt haben. Dazu fehlen auch noch die bereits archivierten Caches.

**Comment by king-ton** [comment]
Gut dann ist es kein Bug ;)
Aber lieber mal die Info, falls es doch einer ist.
