### ISSUE TITLE
Name und Datum in den neusten Beiträgen tauschen

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#102]

**Comment by verfriemelt-dot-org** [comment]
Ich mag das Forum
    easteregg-dd - 20.04.2017 14:49:06

zu
    Ich mag das Forum
    20.04.2017 14:49:06 - easteregg-dd

?

**Comment by king-ton** [comment]
(y)

**Comment by king-ton** [comment]
Ich finde es blöd, dass direkt 2 Links untereinander sind. Leute mit dicken Fingern (ich schaue niemand an :D ) könnten Probleme bekommen.
