### ISSUE TITLE
Filter-Reset fehlt

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#12]
Man befindet sich in der Detail-Ansicht eines Geocaches. Dort mann man auf die SC-Rating-Punktzahl klicken. Nun sollte bestimmt der Cache im SC-Rating angezeigt werden. hat man allerdings unter Geocaches einen Filter gesetzt, wird dieser nicht angezeigt.

Hier wäre es sinnvoll den Filter zurückzusetzen, damit der Geocache im Ranking angezeigt wird..

**Comment by verfriemelt-dot-org** [comment]
du meinst beispielsweise wenn der filter auf traditionalcaches beschränkt ist und man sich einen multicache ansieht und dieser dann entsprechend nicht mit in der liste zu finden ist?

**Comment by king-ton** [comment]
Richtig!

**Comment by verfriemelt-dot-org** [comment]
okay, der cachetype filter wird rausgenommen, wenn around getriggert wird und der cachetyp im filter ein anderer ist, als der cache nach dem gesucht wird.

**Comment by king-ton** [comment]
Bitte das ganze auch noch auf die anderen Filter anwenden. Also auch ein Reset bei Difficulty, Terrain und Region.

**Comment by verfriemelt-dot-org** [comment]
achja, stimmt , die werden ja auch rausgenommen ... hmmmmm *kratz* wahrscheinlich isses dann tatsächlich einfacher, wenn mans komplett resettet.

**Comment by king-ton** [comment]
Vielleicht kann man im Filter generell eine Option einbauen, wo man auswählen kann, ob die Filter gespeichert werden?

**Comment by verfriemelt-dot-org** [comment]
ich hab jetzt nen hinweis einbaut, der erklärt warum der cache nicht in der liste ist mit nem link zum reset. ich denke das is ganz smooth

zum gucken -> such dir nen cache und wähle im filter nen "falschen" landkreis aus. ich denke das is die am wenigst verwirrende lösung.
