### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [verfriemelt-dot-org/sachsencacher#2]
# we need a kick ass design :D

- [x] News-Übersicht
- [x] News-Details
- [x] Geocacher-Übersicht
- [x] Geocacher-Details
- [x] Geocaches-Übersicht
- [x] Geocaches-Details
- [x] FAQ
- [x] Impressum
- [x] Über uns
- [x] Kontakt
- [x] Login-Form

**Comment by king-ton** [comment]
Die Startseite wäre soweit fertig: http://tonifreitag.de/sachsencacher/
Die Ansicht auch Mobilgeräten ist noch nicht beachtet. Ich denke erstmal ist ein einheitliches Design für alle Seiten wichtig. Nicht das es an mir klemmt, dass die Seite nicht produktiv gehen kann ;)

**Comment by rstweb** [comment]
Ich finde des schick. Welche Logos hast du für die Cachetypen genommen? Im Footer muss auf jeden Fall zur Sicherheit noch der Hinweis auf die Datenbasis.

Das Live-gehen wird noch etwas dauern, da heute gegen 17/18Uhr noch bereits archivierte Caches in die DB eingespielt werden und für die natürlich auch noch alle Logs gezogen werden müssen ;-) betrifft etwa 16k an zusätzlichen Caches ^^ wird damit wohl so um die 6-7 Tage noch dauern, bis alle Logeinträge da sind

**Comment by king-ton** [comment]
Also die Icons sind die neuen von Groudspeak: https://www.geocaching.com//play/Content/ui-icons/sprites/cache-types.svg

Ich würde versuchen, die gleich zu verwenden. So sparen wir uns später evtl. Änderungen. Außerdem ist es nur eine SVG-Grafik. Die Vorteile einer solchen sollten bekannt sein ;)

6-7 Tage klingt doch super! Bis dahin ist auch noch Zeit den Rest auf ein akzeptables Niveau zu bringen.

**Comment by king-ton** [comment]
So next page is ready :)

http://tonifreitag.de/sachsencacher/geocaches.html

**Comment by king-ton** [comment]
Ich glaube ich könnte Bretzel-Bäcker werden ;)

http://tonifreitag.de/sachsencacher/geocachers.html

**Comment by rstweb** [comment]
also in Google Chrome zerhaut es das Design bei Geocaches und Geocachers :-(

**Comment by rstweb** [comment]
![sc_design_fehler](https://cloud.githubusercontent.com/assets/25178634/22262189/2a890142-e270-11e6-83c9-956ad66c424e.PNG)

**Comment by king-ton** [comment]
Aktualisiere mal das Stylesheet: http://tonifreitag.de/sachsencacher/assets/css/style.css
Dann sollte es passen...

**Comment by rstweb** [comment]
Jetzt haut es hin ^^

**Comment by rstweb** [comment]
heute ist hier echt der wurm drin: dns-fehler en gros und trotz zwangs-refresh wollte der vorhin nicht, aber jetzt :-)

**Comment by king-ton** [comment]
http://tonifreitag.de/sachsencacher/login.html

So das letzte für heute. Morgen geht es mit den Detail-Seiten weiter.

**Comment by king-ton** [comment]
Hab mal noch eine ToDo-Liste für mich eingebaut :)

**Comment by rstweb** [comment]
im git geändert:
Startseite mit Elementen
Liste Geocacher
Liste Geocaches

noch zu machen an diesen Seiten:
Html.tpl.php -> aktuellen Menu-Punkt hervorheben (<li class="nav-item"> <-> <li class="nav-item active">)
Filter->Region-><optgroup label="Region Chemnitz">
Filter->strukturieren
Geocaches -> Suchfeld

**Comment by king-ton** [comment]
Bitte auch noch `.twitter-typeahead` aus dem Stylesheet übernehmen.

**Comment by king-ton** [comment]
Nächste Seite ist fertig: http://tonifreitag.de/sachsencacher/news-details.html

Bitte mal den Debug-Log am Ende der Seite wie folgt ändern: `<pre class="debug"></pre>`
Dann kann man es auch wieder lesen ;)

**Comment by rstweb** [comment]
Das Admin-Login würde ich im aktuellen Design lassen, das sieht m.E. schon gut so aus. Ich würde aber den Admin-Login quasi auf Halde nehmen, falls wir den Adminbereich aus dem generell Seitenlayout rausnehmen und einen separaten Adminbereich machen werden

**Comment by king-ton** [comment]
Ich kanns auch so machen, dass man es ins Base-Template integrieren kann. Das wäre kein Aufwand. Aber wir können es auch gerne erstmal so lassen, mir ist es egal...

**Comment by rstweb** [comment]
lieber erstmal lassen. hängt mit der art der Erstellung des Formulars zusammen ;-)

**Comment by rstweb** [comment]
News-Details ist auch im git, ich muss hier aber noch einen zusätzlichen View für news/show/ machen, da mit dem derzeitigen Aufbau das wrappen eher suboptimal ist
komischerweise ist die Schrift noch falsch

**Comment by king-ton** [comment]
So es gibt neue Icons für die Cachegrößen:

http://tonifreitag.de/sachsencacher/geocaches.html

**Comment by king-ton** [comment]
So ich habe fertig :)
