### ISSUE TITLE
Performance Geocacher-Liste

### ISSUE THREAD

**Issue by rstweb** [verfriemelt-dot-org/sachsencacher#23]
laden dauert ziemlich lange

**Comment by verfriemelt-dot-org** [comment]
ich hab da mal ne memcached schicht eingezogen;
an sich wird der dicke querie da ohnehin im mysql cache gehalten, das is auch an sich okay so.
nur da gerade die daten permanent neu geschrieben werden, wir der cache auch immer wieder invalidiert und damit dauert die anfrage für die zwei dicken queries doch recht lange.

die memcached schicht hält die daten jetzt für alle seiten mit einmal für aktuell 5 minuten zwischen. sprich wenn da einer ankommt wirds allenfalls nur einmal kurz langsam sein und in zukunft im livebetrieb wird das nur in der nacht beim einlesen von neuen daten der fall sein. und selbst wenn der cache aus irgend nem grund stale is , wird der querie dann nur einmal gezogen und dann direkt in sql und memcached zwischen gespeichert.
