### ISSUE TITLE
listensuche ungünstig plaziert.

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [verfriemelt-dot-org/sachsencacher#25]
wir müssen mal die suchleiste besser positionieren auf den listen seiten.
die gefilterte suche steht in konkurrenz mit der globalen suche und verwirrt an der stelle etwas, das muss vom design her klar sein, um was es da geht.

**Comment by king-ton** [comment]
Dir Frage ist, brauchen wir die Listen-Suche? Weil theoretisch deckt sie genau das gleiche ab, wie die Globale suche nur, dass nur Geocacher oder Geocaches angezeigt werden.
Sonst wurde ich es versuchen direkt in die Tabelle zu integrieren, um zu zeigen, dass die Suche auf die Tabelle angewandt wird.

**Comment by verfriemelt-dot-org** [comment]
die suche spuckt dir den geocacher ( noch nicht ) und geocache ( schon ) in der liste aus um die "umgebung" zu zeigen, ähnlich wie die verlinkung der SC punkte auf der geoache detailseite.

**Comment by king-ton** [comment]
So ich denke jetzt ist die Zuordnung besser.
