### ISSUE TITLE
Fehlermeldung neuer Kommentar

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#26]
Aktuell wird ein Feld rot umrandet, wenn man es absendet, aber es leer ist. Könnte man noch eine exakte Fehlermeldung einbauen? Bspw. als Untertitel: "Dieses Feld darf nicht leer sein."
Außerdem wäre es sinnvoll dann wieder auf der Seite nach unten zu springen. Aktuell landet man auf der Seite ganz oben und wenn man es nicht prüft, kann man denen, dass der Kommentar erstellt wurde.

**Comment by verfriemelt-dot-org** [comment]
ich hab mal nen jumper zum kommtentarformular beim submit eingebaut. ich denke mehr als rot ist nen bissl overkill bei nem leeren feld :D
aber man kann generell die klasse dahingehend erweiteren, dass man fehlermeldungen für formularfelder anzeigen lassen kann. aber das wäre nen etwas größes projekt und ich denke hier nicht notwendig.

**Comment by king-ton** [comment]
Bei einem leeren Feld ist es vollkommen ausreichend. Ich bin aber der Meinung, dass man ein Validationssystem später nochmal genauers ins Auge gefasst werden sollte. Aber da kann man bei Gelegenheit noch ein eigenes Ticket aufmachen.
