### ISSUE TITLE
Statbar für Geocacher

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#31]
Auch für Geocacher sollen sich wieder Statistik-Banner erzeugen lassen. Dabei soll man zwischen den einzelnen Regionen wählen können.

**Comment by verfriemelt-dot-org** [comment]
/index.php/statsbar/geocacher/6260301/3/1.png
/index.php/statsbar/geocacher/6260301/3/0.png
schema: cacherId/districtId/skipArchived

wobei /index.php/statsbar/geocacher/6260301.png als shorthand auch geht

cachebusting mit ?skipcache

baust du das ins frontend mit ein?
