### ISSUE TITLE
Archivierte Caches unter Geocacher ausblenden

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#32]
Ich persönlich würde mich sehr freuen, wenn es die Geocacher-Statistik auch ohne die archivierten Caches gibt.
Einige Geocacher sind noch nicht so lange dabei. Diese können natürlich die archivierten Caches nicht mehr finden und somit hätte sie nie die Cache an den "Oldies" vorbei zu kommen, auch wenn sie bspw. alle Caches in einer Region gefunden hätten. Die Anzahl der nicht mehr zu findenden Caches wird ja nicht weniger. In Sachsen gab es laut DB 39.765 Caches. Davon sind aber nur noch 23.542 aktiv. Damit sind etwa 40% archiviert, was ich persönlich doch eine ganz schöne Menge finde.

Andere würden natürlich wieder sagen: Aber es ist doch unfair. Ich habe die Caches irgendwann mal gefunden, wieso soll ich jetzt dafür bestraft werden, dass sich der Owner darum kümmert und ihn archiviert.

Was meint ihr dazu? Sollten wir einfach beides anbieten und das auch auf den Bannern verdeutlichen?

**Comment by verfriemelt-dot-org** [comment]
+1

**Comment by verfriemelt-dot-org** [comment]
done, auch wenn etwas nich so schön gebaut, die geocacherlisten domain braucht auf jeden fall mal bissl refactoring :D
