### ISSUE TITLE
index.php aus URL entfernen

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#35]
Das index.php in der URL sieht hässlich aus ;)
Ich denke das sollten wir noch per Rewrite entfernen.

**Comment by verfriemelt-dot-org** [comment]
hm, da bin ich etwas zwiegespalten.

punkt 1) is die pathinfo methode deutlich schneller ;D
punkt 2) wenn wir das mit modrewrite umsetzen nageln wir uns selbst erstmal apache fest und wir können locales debugging nichtmehr mit dem phpserver umsetzen, was an sich schade ist.

können wir uns noch überlegen; aber ich habs explizit bisher nicht getan.

**Comment by king-ton** [comment]
Bei mir lokal habe ich es umgesetzt. Ich arbeite aber auch direkt mit dem Apache. Ist aber auch immer eine Ansichtssache. Mich persönlich stört sowas immer, aber das ist meine Meinung.

**Comment by rstweb** [comment]
aus meiner Sicht geht es gut mit index.php; rewrite würde auch für nginx gehen, aber tatsächlich nutze ich auch den php-webserver zum entwickeln und da wäre es suboptimal

wir sollten uns aber grundsätzlich einigen, da ein paar Weiterleitungen von Formularen noch nicht passen (bspw. FAQ-Edit)

**Comment by king-ton** [comment]
Wenn ihr beide mit den php internen Server arbeitet, würde ich es fast so lassen. Mir ist es gleich. Ich mag nur schöne URLs :)
Nach dem Login kommt bspw. auch ein falscher Redirect.

**Comment by king-ton** [comment]
Bleibt so.
