### ISSUE TITLE
Kommentar: Sprung zum neu erstellten Kommentar

### ISSUE THREAD

**Issue by rstweb** [verfriemelt-dot-org/sachsencacher#36]
Es wäre sicherlich cool, wenn man direkt zum neu erstellten Kommentar springen würde, nachdem ein Kommentar erfolgreich eingetragen wurde. Bislang erfolgt der Sprung zur Marke #comments, aber die Marke ist nirgends gesetzt

**Comment by verfriemelt-dot-org** [comment]
ist mit drin, bei der gelegenheit hab ich das news formular auch mal aufgeräumt
