### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#41]
Aktuell werden alle nicht vorhandenen Seiten auf eine sehr leere search-Seite weitergeleitet.
Ich würde sagen, wir schreiben was hin, dass es die Seite nicht gibt und machen darunter ein Suchformular, wobei das würde sich dann mit dem Suchformular in der Navbar decken?

**Comment by rstweb** [comment]
das ist ja die generelle Frage, wie wir mir der seitenweiten Suche vorgehen wollen; optimal wäre ja quasi eine Suche über die Seiten nebst FAQ und Blog, sowie durch Geocaches und Geocacher

**Comment by rstweb** [comment]
eine einfache 404 baue ich dann mal ein

**Comment by rstweb** [comment]
eine quick&dirty-Variante ist im git; ich muss die Seite nochmal mit einem schönen Text füllen. Außerdem müsste noch ein Suchfeld rein; ich dachte da an ein vergleichbares wie das oben im Navigationsmenü
