### ISSUE TITLE
Last Founds in Geocache-Details

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#42]
Ich glaube hier sollte die Tabelle komplett neu aufgebaut werden. Statt Rang würde ich hier Fundnummer nehmen. Der Name und Anzahl der Funde ist in Ordnung, aber statt der Fundstatistiken würde ich lieber noch das Funddatum angeben und ob man evtl. ob man einen Favi vergeben hat. Was haltet ihr davon?

**Comment by verfriemelt-dot-org** [comment]
klingt super!

**Comment by verfriemelt-dot-org** [comment]
wollen wir alle fundtypen inkludieren? also vorallem auch DNFs ? fände ich gut, weil dann sieht man relativ zügig auch möglicherweise bald tote caches.
