### ISSUE TITLE
Suche für Geocacher in Geocacher-Table

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#43]
in der Liste aller Geocacher soll man nach bestimmten Namen suchen können.

**Comment by verfriemelt-dot-org** [comment]
die suche ist prinzipiell da, jetzt müsste man sich noch nen objekt bauen, was mir die position von dem cacher raussucht und dann können wir die genauso in der liste anzeigen wie sonst auch.
die listensuche ist analog der cacheliste auch in abhännigkeit vom aktuellen filter.
damit können wir für die zukunft auch relativ einfach nachbauen, dass der cache an der stelle nicht deaktivert sein darf.

**Comment by verfriemelt-dot-org** [comment]
fast, nur noch das highlight in der liste und dann ist das problem erledigt.
