### ISSUE TITLE
Angabe Datenquelle des Diagramms in Geocacher-Detail

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#46]
Ich würde es noch hilfreich finden (um Verwirrungen vorzubeugen), dass im Diagramm angegeben wird, dass dies nur die Daten für Sachsen sind. Ja klar, die Seite heißt nicht umsonst sachsencacher, aber bspw. werden bei der Fundzahl auch alle berücksichtigt.

**Comment by rstweb** [comment]
die Werte sind ja je Region; Vorschlag: "Fund-Logs je Monat in Region"?

**Comment by king-ton** [comment]
Wir können natürlich auch noch einen Regionsfilter einbauen. Dann ist die Angabe der Region überflüssig.

**Comment by rstweb** [comment]
aber erstmal reicht es ja so

**Comment by king-ton** [comment]
Das war auch nicht für jetzt gedacht, sondern für später. Sonst hätte ich es zum Milestone hinzugefügt ^^
Dinge die man auf jeden Fall umsetzen sollte, mache ich immer gleich als Ticket. Was Ideen sind, über die man nochmal reden sollte, schreibe ich in die Liste.
