### ISSUE TITLE
geocacher founds in district buggy oder daten falsch

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [verfriemelt-dot-org/sachsencacher#51]
in der stadt dresden mit rein unarchivierten caches hat bergfex
1736 von 1730

caches gefunden :D das is etwas seltsam, müssen wir uns genauer angucken, was da los ist.

**Comment by king-ton** [comment]
Doppellogs? Checkt der Collector auch, wenn ein Log gelöscht wird?

**Comment by verfriemelt-dot-org** [comment]
¯\_(ツ)_/¯

**Comment by verfriemelt-dot-org** [comment]
ein teil was ich noch rausrechnen konnte sind doppellogs, allerdings reicht das nicht aus um den fehler zu bereiningen.

**Comment by verfriemelt-dot-org** [comment]
alles klar, beim abziehen der eigenen caches wurden die archivierten caches beim entsprechend gesetzten filter noch mitgezählt. daher entstand der fehler.
