### ISSUE TITLE
Statbar für keinen Fund in Region

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#60]
Aktuell wird nichts angezeigt, wenn der Cacher keinen Fund in der Region hat. Hier könnte man stattdessen 0 Funde anzeigen und letzter Rang + 1.

**Comment by verfriemelt-dot-org** [comment]
ich hab jetzt einfach hingeschrieben, dass es gar keine funde gibt. immerhin wird das eh keiner wirklich ernsthaft nutzen. nur das es nich kaputt aussieht.
