### ISSUE TITLE
Deaktivierte Geocaches kennzeichnen

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#63]
In den Geocache-Tabellen und auf den Detail-Seiten sollen Caches gekennzeichnet werden, welche deaktiviert (nicht verfügbar) sind. Außerdem soll ein unterschied zu deaktivierten Caches deutlich werden.

**Comment by verfriemelt-dot-org** [comment]
das is so eine triviale änderung, dass ich die direkt als .8 release
