### ISSUE TITLE
Pagination und Filter Fehler

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#74]
Der Kollege DD-JC ist fleißig am testen und hat etwas festgestellt:

Bedienszenario
1. "Geocaches" im Hauptmenü aufrufen
2. auf Seite 1580 (resp. die letzte) gehen
3. Filter "archivierte einbeziehen: nein" setzen und bestätigen
4. Fehlerchen: keine Funde "Der derzeit gesetzte Filter ergibt keine Caches! "

Vermutung
siehe Adresszeile "...index.php/list/geocaches/1580"
die letzte Seite muss ja nun leer sein...

Korrekturmöglichkeit
Beim Aktivieren (sicher auch beim Deaktivieren) eines Filters die angeforderte Seite zurücksetzen.

Meine Anmerkung: Ich denke auch, dass es sinnvoll ist, einfach den Filter nach der Seite zu Reseten. Also nachdem der Filter betätigt wurde, landet man immer auf Seite 1.

**Comment by verfriemelt-dot-org** [comment]
> Ich denke auch, dass es sinnvoll ist, einfach den Filter nach der Seite zu Reseten. Also nachdem der Filter betätigt wurde, landet man immer auf Seite 1.

:+1:
