### ISSUE TITLE
"Grenzwärtuge" Caches in Sachsen

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#75]
Es gibt Caches, diese werden auf gc.com unter Sachsen geführt. Allerdings liegen deren Listing-Koordinaten auf der Grenze bzw. außerhalb von Sachsen. Wie wollen wir mit solchen Caches verfahren?

**Mein Vorschlag**
Primär zählt das ausgewählte Bundesland von gc.com. Sollte der Cache allerdings außerhalb von Sachsen liegen, zählt der naheliegendste Landkreis?
So werden wirklich alle sächsischen Caches und auch Grenzfälle wie bspw. dieser hier ( https://sachsencacher.de/index.php/detail/geocache/GC66HYK ) berücksichtigt.

**Comment by verfriemelt-dot-org** [comment]
die caches kann man direkt aufrufen weiterhin, wenn die in unserer db sind.
das sollten wir noch abschalten.
aber in der suche und listing tauchen die vorerst nichtmehr auf.

**Comment by verfriemelt-dot-org** [comment]
hmm, laut den aktuellen coords liegt der ja innerhalb von sachsen, und wir verwenden ja ohnehin unsre eigene lokalisierung . vondaher, was ausserhalb von sachsen ist wird bei sc nicht berücksichtigt.
damit ist das problem ja auch erstmal hinfaellig da es uns egal ist, was bei gc hinterlegt ist
