### ISSUE TITLE
Notify-Handler

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#77]
So langsam bin ich der Meinung sollten wir noch etwas integrieren, um Fehlermeldungen anzeigen zu lassen. Wie stelle ich es mir vor:

Es sollte eine Funktion geben, der man Art des Fehlers (Success, Warnung, Info oder Fehler), eine Meldung und eine MeldungsId übergeben kann. Die Meldungen sind dann nur für den aktuellen Request verfügbar. Über Funktionen kann man abfragen, ob Fehler vorhanden sind. Falls welche vorhanden sind, werden die am Anfang der Seite ausgegeben.
Wozu die ID? So könnte man auch einzelne Felder markieren, falls eine EIngabe fehlt oder diese falsch ist.

**Comment by verfriemelt-dot-org** [comment]
du meinst das im bezug auf formulare und ungueltige eingaben?

**Comment by king-ton** [comment]
Beispielsweise. Aber auch fehlende Berechtigungen.
Deshalb global, weil es sich nicht direkt zuordnen lässt

**Comment by verfriemelt-dot-org** [comment]
und bitte :D
