### ISSUE TITLE
Erweiterung Rollen

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#79]
Admin-Rolle sollte nicht löschbar sein. Evtl. Spalte in DB mit Locked?
Ich würde auch gleich noch einen Ausführlichen Namen in die DB mit einbauen. Sowas könnte man dann im Forum verwenden als Titel verwenden. Bspw. Administrator, Moderrator, Premium Member, Basic Member, Charter Member.

**Comment by verfriemelt-dot-org** [comment]
ist die frage ob wir den locked flag wirklich brauchen, im zweifel stellen wir das händisch in der db wieder her :D da müssten wir enige male den admin accout löschen, damit wir das wirklich vom aufwand her rechtfertigen können.
man könnte einfach das löschen der ID 1 verbieten und ist durch ;)

**Comment by king-ton** [comment]
Wobei da hast du recht. Man könnte es ja auch so machen,  dass die Rolle admin min. einen Benutzer haben muss. Und Rollen können nicht gelöscht werden, wenn sie noch Benutzer enthalten. Damit würde es nicht zu einer Löschung kommen.
Allerdings würde ich die Rolle im Setup mit ergänzen.

**Comment by verfriemelt-dot-org** [comment]
die admin rolle is schon ins git gewandert und weist uns drei als admins aus. ;)
