### ISSUE TITLE
Pagination-Problem bei Geocacher

### ISSUE THREAD

**Issue by king-ton** [verfriemelt-dot-org/sachsencacher#85]
Das ist die letzte Seite: https://www.sachsencacher.de/index.php/list/geocachers/5937
Allerdings wird noch eine weitere Seite angezeigt?

**Comment by verfriemelt-dot-org** [comment]
das beispiel is nichmehr valide :D

**Comment by verfriemelt-dot-org** [comment]
¯\_(ツ)_/¯
