### ISSUE TITLE
Regionsauswahl auf Sachsen beschränken

### ISSUE THREAD

**Issue by rstweb** [verfriemelt-dot-org/sachsencacher#9]
Es sollten in der Regionsauswahl nur Sachsen und deren Unterteilungen angezeigt werden

**Comment by rstweb** [comment]
potentiell sind die Zuordnungen ind er DB nicht richtig erfolgt

**Comment by king-ton** [comment]
Das erklärt bestimmt auch, dass der Regionsfilter unter Geocaches nicht richtig funktioniert?
Zumindest wenn man Region Chemnitz, Leipzig und Dresden auswählt

**Comment by verfriemelt-dot-org** [comment]
fixed ;D
